# Generated by Django 5.0.1 on 2024-02-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0005_about_delete_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="image",
            field=models.ImageField(upload_to="media/about"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="doc_image",
            field=models.ImageField(upload_to="Doctors"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to="media/slider"),
        ),
    ]
